language: cpp
sudo: true
dist: bionic

# Define the build matrix
compiler:
  - gcc
  - clang

os:
  - linux
  - mac

osx_image:
  - xcode9.4
  - xcode10
  - xcode10.3
  - xcode11
  - xcode11.3

env:
  jobs:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release
    - BUILD_TYPE=Install
  global:
    PYTHONPATH: ${TRAVIS_BUILD_DIR}/build/py
    PY_CMD: python3
    LD_LIBRARY_PATH: /usr/lib/llvm-7/lib/

# Define some additional jobs building on MacOS
jobs:
  exclude:
    - os: mac
      osx_image: xcode9.4
      compiler: gcc
    - os: mac
      osx_image: xcode10
      compiler: gcc
    - os: mac
      osx_image: xcode10.3
      compiler: gcc
    - os: mac
      osx_image: xcode11
      compiler: gcc
    - os: mac
      env: BUILD_TYPE=Debug
    - os: mac
      osx_image: xcode9.4
      env: BUILD_TYPE=Install
    - os: mac
      osx_image: xcode10
      env: BUILD_TYPE=Install
    - os: mac
      osx_image: xcode10.3
      env: BUILD_TYPE=Install
    - os: mac
      osx_image: xcode11
      env: BUILD_TYPE=Install

  include:
    - os: osx
      osx_image: xcode11.3
      compiler: gcc
      env:
        CC: gcc-9
        CXX: g++-9
        BUILD_TYPE: Release
    - os: osx
      osx_image: xcode11.3
      compiler: gcc
      env:
        CC: gcc-9
        CXX: g++-9
        BUILD_TYPE: Install
    - os: osx
      osx_image: xcode11.3
      compiler: clang
      env:
        BUILD_TYPE: Install

    - os: linux
      compiler: gcc
      env:
        CC: gcc-5
        CXX: g++-5
        BUILD_TYPE: Release
    - os: linux
      compiler: gcc
      env:
        CC: gcc-6
        CXX: g++-6
        BUILD_TYPE: Release
    - os: linux
      compiler: gcc
      env:
        CC: gcc-8
        CXX: g++-8
        BUILD_TYPE: Release
    - os: linux
      compiler: gcc
      env:
        CC: gcc-9
        CXX: g++-9
        BUILD_TYPE: Release
##    - os: linux
##      compiler: clang
##      env:
##        CC: clang-3.8
##        CXX: clang++-3.8
##        BUILD_TYPE: Release
    - os: linux
      compiler: clang
      env:
        CC: clang-3.9
        CXX: clang++-3.9
        BUILD_TYPE: Release
    - os: linux
      compiler: clang
      env:
        CC: clang-4.0
        CXX: clang++-4.0
        BUILD_TYPE: Release
    - os: linux
      compiler: clang
      env:
        CC: clang-5.0
        CXX: clang++-5.0
        BUILD_TYPE: Release
    - os: linux
      compiler: clang
      env:
        CC: clang-6.0
        CXX: clang++-6.0
        BUILD_TYPE: Release
    - os: linux
      compiler: clang
      env:
        CC: clang-8
        CXX: clang++-8
        BUILD_TYPE: Release
    - os: linux
      compiler: clang
      env:
        CC: clang-9
        CXX: clang++-9
        BUILD_TYPE: Release

# Handle git submodules yourself
git:
  submodules: false

# Only run on master  
branches:
  only:
  - master
  - develop

# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i.bak 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - $PY_CMD --version
  - $PY_CMD -m pip install --user --upgrade pip wheel setuptools

addons:
  apt:
    sources:
      - sourceline: "ppa:ubuntu-toolchain-r/test"
    packages:
      - python3-dev
      - python3-pip
      - python3-setuptools
      - lcov
      - libclang-7-dev
 

install:
  - $PY_CMD -m pip install --user -r requirements.dev.txt
  - $PY_CMD -m pip install --user -r requirements.txt
  - |
    if ${GCC} --version
    then
      sudo apt-get install ${CXX}
    fi

script:
  - cd ${TRAVIS_BUILD_DIR}
  - ./.travis_script.sh

after_success:
  # Skip this unless on a debug build
  - if [ ${BUILD_TYPE} != "Debug" ]; then exit 0; fi
  - if [ ${TRAVIS_OS_NAME} != "linux" ]; then exit 0; fi
  - cd ${TRAVIS_BUILD_DIR}/build_coverage
  # Capture coverage info
  - lcov --directory . --capture --output-file coverage.info
  # Filter out system libraries and dependencies
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info
  - lcov --remove coverage.info '${TRAVIS_BUILD_DIR}/thirdparty/*' --output-file coverage.info
  # Print coverage stats to the screen, for debug purposes
  - lcov --list coverage.info
  - $PY_CMD -m coverage report
  # Upload report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
