language: cpp
sudo: true
dist: xenial

# Define the build matrix
compiler:
  - gcc
  - clang

os:
  - linux
  # - osx - #not working, fix later :(

env:
  jobs:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release
    - BUILD_TYPE=Install
  global:
    PYTHON: 3.7
    PYTHONPATH: ${TRAVIS_BUILD_DIR}/build/py
    PY_CMD: python${PYTHON}
    LD_LIBRARY_PATH: /usr/lib/llvm-3.8/lib/

# Handle git submodules yourself
git:
  submodules: false

# Only run on master  
branches:
  only:
  - master

# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i.bak 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - $PY_CMD -m pip install --user --upgrade pip wheel setuptools

addons:
  apt:
    sources:
      - deadsnakes
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - python3.7-dev
      - python3-pip
      - python3-setuptools
      - lcov
      - g++-6
      - clang-3.8
      - libclang-3.8-dev

install:
  - $PY_CMD -m pip install --user -r requirements.dev.txt
  - $PY_CMD -m pip install --user -r requirements.txt

script:
  - cd ${TRAVIS_BUILD_DIR}
  - ./.travis_script.sh

after_success:
  # Skip this unless on a debug build
  - if [ ${BUILD_TYPE} != "Debug" ]; then exit 0; fi
  - cd ${TRAVIS_BUILD_DIR}/build_coverage
  # Capture coverage info
  - lcov --directory . --capture --output-file coverage.info
  # Filter out system libraries and dependencies
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info
  - lcov --remove coverage.info '${TRAVIS_BUILD_DIR}/thirdparty/*' --output-file coverage.info
  # Print coverage stats to the screen, for debug purposes
  - lcov --list coverage.info
  # Upload report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
