language: cpp
sudo: true
dist: xenial

# Handle git submodules yourself
git:
  submodules: false

# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i.bak 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - PY_CMD=python3.7
  - $PY_CMD -m pip install --user --upgrade pip wheel setuptools

compiler:
  - gcc
  - clang

os:
  - linux
  # - osx - #not working, fix later :(

addons:
  apt:
    sources:
      - deadsnakes
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - python3.7-dev
      - python3-pip
      - lcov
      - g++-6
      - clang-3.8

branches:
  only:
  - master

install:
  - "[ $CXX = g++ ] && export CXX=g++-6 || true"
  - "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"
  - $PY_CMD -m pip install --user -r requirements.dev.txt
  - $PY_CMD -m pip install --user -r requirements.txt

env: PYTHON=3.7 PYTHONPATH=${TRAVIS_BUILD_DIR}/build/py

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -DBUILD_PY_BINDINGS=ON ..
  - make -j4
  - cd ${TRAVIS_BUILD_DIR}
  - ./build/bin/peakingduckcpptests
  - mkdir build_coverage
  - cd build_coverage
  - cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON ..
  - make -j4
  - cd ${TRAVIS_BUILD_DIR}
  - pytest --pdb --tb=long ./tests/py/testsuite.py

after_success:
  - cd ${TRAVIS_BUILD_DIR}/build_coverage
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  - lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"