coverage:
  precision: 2
  round: down
  
  ignore:
    - "tests/"  # ignore folders and all its contents
    - "test_*"  # wildcards accepted
    - "py/peakingduck.cpp" # ignore the pybind wrapper     

codecov:
  token: 924f9e75-5768-420a-88d3-c48457a4cdba